var annotated_dup =
[
    [ "Gpio2", "namespace_gpio2.html", [
      [ "Chip", "class_gpio2_1_1_chip.html", "class_gpio2_1_1_chip" ],
      [ "ChipInfo", "struct_gpio2_1_1_chip_info.html", "struct_gpio2_1_1_chip_info" ],
      [ "Line", "class_gpio2_1_1_line.html", "class_gpio2_1_1_line" ],
      [ "LineAttribute", "struct_gpio2_1_1_line_attribute.html", "struct_gpio2_1_1_line_attribute" ],
      [ "LineConfig", "struct_gpio2_1_1_line_config.html", "struct_gpio2_1_1_line_config" ],
      [ "LineConfigAttribute", "struct_gpio2_1_1_line_config_attribute.html", "struct_gpio2_1_1_line_config_attribute" ],
      [ "LineEvent", "struct_gpio2_1_1_line_event.html", "struct_gpio2_1_1_line_event" ],
      [ "LineInfo", "struct_gpio2_1_1_line_info.html", "struct_gpio2_1_1_line_info" ],
      [ "LineRequest", "struct_gpio2_1_1_line_request.html", "struct_gpio2_1_1_line_request" ],
      [ "LineValues", "struct_gpio2_1_1_line_values.html", "struct_gpio2_1_1_line_values" ]
    ] ],
    [ "Piduino", "namespace_piduino.html", [
      [ "_Setpriority", "struct_piduino_1_1___setpriority.html", "struct_piduino_1_1___setpriority" ],
      [ "BashCompletionOptionPrinter", "class_piduino_1_1_bash_completion_option_printer.html", "class_piduino_1_1_bash_completion_option_printer" ],
      [ "Clock", "class_piduino_1_1_clock.html", "class_piduino_1_1_clock" ],
      [ "ConfigFile", "class_piduino_1_1_config_file.html", "class_piduino_1_1_config_file" ],
      [ "Connector", "class_piduino_1_1_connector.html", "class_piduino_1_1_connector" ],
      [ "ConsoleOptionPrinter", "class_piduino_1_1_console_option_printer.html", "class_piduino_1_1_console_option_printer" ],
      [ "Convert", "class_piduino_1_1_convert.html", "class_piduino_1_1_convert" ],
      [ "Converter", "class_piduino_1_1_converter.html", "class_piduino_1_1_converter" ],
      [ "Database", "class_piduino_1_1_database.html", "class_piduino_1_1_database" ],
      [ "Fifo", "class_piduino_1_1_fifo.html", "class_piduino_1_1_fifo" ],
      [ "FileDevice", "class_piduino_1_1_file_device.html", "class_piduino_1_1_file_device" ],
      [ "FileStream", "class_piduino_1_1_file_stream.html", "class_piduino_1_1_file_stream" ],
      [ "Flags", "class_piduino_1_1_flags.html", "class_piduino_1_1_flags" ],
      [ "Gpio", "class_piduino_1_1_gpio.html", "class_piduino_1_1_gpio" ],
      [ "GpioDevice", "class_piduino_1_1_gpio_device.html", "class_piduino_1_1_gpio_device" ],
      [ "GpioPwm", "class_piduino_1_1_gpio_pwm.html", "class_piduino_1_1_gpio_pwm" ],
      [ "GroffOptionPrinter", "class_piduino_1_1_groff_option_printer.html", "class_piduino_1_1_groff_option_printer" ],
      [ "I2cDev", "class_piduino_1_1_i2c_dev.html", "class_piduino_1_1_i2c_dev" ],
      [ "Implicit", "class_piduino_1_1_implicit.html", "class_piduino_1_1_implicit" ],
      [ "invalid_option", "class_piduino_1_1invalid__option.html", "class_piduino_1_1invalid__option" ],
      [ "IoDevice", "class_piduino_1_1_io_device.html", "class_piduino_1_1_io_device" ],
      [ "IoMap", "class_piduino_1_1_io_map.html", "class_piduino_1_1_io_map" ],
      [ "LinearBuffer", "class_piduino_1_1_linear_buffer.html", "class_piduino_1_1_linear_buffer" ],
      [ "Manufacturer", "class_piduino_1_1_manufacturer.html", "class_piduino_1_1_manufacturer" ],
      [ "Max1161x", "class_piduino_1_1_max1161x.html", "class_piduino_1_1_max1161x" ],
      [ "Max7311", "class_piduino_1_1_max7311.html", "class_piduino_1_1_max7311" ],
      [ "Mcp4725", "class_piduino_1_1_mcp4725.html", "class_piduino_1_1_mcp4725" ],
      [ "Mcp4728", "class_piduino_1_1_mcp4728.html", "class_piduino_1_1_mcp4728" ],
      [ "Option", "class_piduino_1_1_option.html", "class_piduino_1_1_option" ],
      [ "OptionParser", "class_piduino_1_1_option_parser.html", "class_piduino_1_1_option_parser" ],
      [ "OptionPrinter", "class_piduino_1_1_option_printer.html", "class_piduino_1_1_option_printer" ],
      [ "Pin", "class_piduino_1_1_pin.html", "class_piduino_1_1_pin" ],
      [ "RingBuffer", "class_piduino_1_1_ring_buffer.html", "class_piduino_1_1_ring_buffer" ],
      [ "Scheduler", "class_piduino_1_1_scheduler.html", "class_piduino_1_1_scheduler" ],
      [ "SerialPort", "class_piduino_1_1_serial_port.html", "class_piduino_1_1_serial_port" ],
      [ "SoC", "class_piduino_1_1_so_c.html", "class_piduino_1_1_so_c" ],
      [ "SocPwm", "class_piduino_1_1_soc_pwm.html", "class_piduino_1_1_soc_pwm" ],
      [ "SpiDev", "class_piduino_1_1_spi_dev.html", "class_piduino_1_1_spi_dev" ],
      [ "Switch", "class_piduino_1_1_switch.html", "class_piduino_1_1_switch" ],
      [ "SysLog", "class_piduino_1_1_sys_log.html", "class_piduino_1_1_sys_log" ],
      [ "SysLogBuffer", "class_piduino_1_1_sys_log_buffer.html", "class_piduino_1_1_sys_log_buffer" ],
      [ "System", "class_piduino_1_1_system.html", "class_piduino_1_1_system" ],
      [ "Terminal", "class_piduino_1_1_terminal.html", "class_piduino_1_1_terminal" ],
      [ "TerminalNotifier", "class_piduino_1_1_terminal_notifier.html", "class_piduino_1_1_terminal_notifier" ],
      [ "ThreadSafeBuffer", "class_piduino_1_1_thread_safe_buffer.html", "class_piduino_1_1_thread_safe_buffer" ],
      [ "TSQueue", "class_piduino_1_1_t_s_queue.html", "class_piduino_1_1_t_s_queue" ],
      [ "Value", "class_piduino_1_1_value.html", "class_piduino_1_1_value" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "_Unique_if", "structstd_1_1___unique__if.html", "structstd_1_1___unique__if" ],
      [ "_Unique_if< T[]>", "structstd_1_1___unique__if_3_01_t_0f_0e_4.html", "structstd_1_1___unique__if_3_01_t_0f_0e_4" ],
      [ "_Unique_if< T[N]>", "structstd_1_1___unique__if_3_01_t_0f_n_0e_4.html", "structstd_1_1___unique__if_3_01_t_0f_n_0e_4" ]
    ] ],
    [ "gpio_v2_line_attribute", "classgpio__v2__line__attribute.html", null ],
    [ "gpio_v2_line_config", "classgpio__v2__line__config.html", null ],
    [ "gpio_v2_line_config_attribute", "classgpio__v2__line__config__attribute.html", null ],
    [ "gpio_v2_line_event", "classgpio__v2__line__event.html", null ],
    [ "gpio_v2_line_info", "classgpio__v2__line__info.html", null ],
    [ "gpio_v2_line_request", "classgpio__v2__line__request.html", null ],
    [ "gpio_v2_line_values", "classgpio__v2__line__values.html", null ],
    [ "gpiochip_info", "classgpiochip__info.html", null ],
    [ "Private", "class_private.html", null ]
];