BEGIN TRANSACTION;
INSERT INTO "arch" VALUES (-1,'Unknown');
INSERT INTO "arch" VALUES (0,'ARM');
INSERT INTO "board_family" VALUES (-1,'Unknown',NULL,NULL,NULL);
INSERT INTO "board_family" VALUES (0,'RaspberryPi','/dev/i2c-%d','/dev/spidev%d.%d','/dev/ttyAMA%d');
INSERT INTO "board_family" VALUES (1,'NanoPi','/dev/i2c-%d','/dev/spidev%d.%d','/dev/ttyS%d');
INSERT INTO "board_family" VALUES (2,'OrangePi','/dev/i2c-%d','/dev/spidev%d.%d','/dev/ttyS%d');
INSERT INTO "board_family" VALUES (3,'BananaPi','/dev/i2c-%d','/dev/spidev%d.%d','/dev/ttyS%d');
INSERT INTO "connector_family" VALUES (0,'Header1X',1);
INSERT INTO "connector_family" VALUES (1,'Header2X',2);
INSERT INTO "manufacturer" VALUES (-1,'Unknown');
INSERT INTO "manufacturer" VALUES (0,'Broadcom');
INSERT INTO "manufacturer" VALUES (1,'Sony UK');
INSERT INTO "manufacturer" VALUES (2,'Qisda');
INSERT INTO "manufacturer" VALUES (3,'Egoman');
INSERT INTO "manufacturer" VALUES (4,'Embest');
INSERT INTO "manufacturer" VALUES (5,'Allwinner');
INSERT INTO "manufacturer" VALUES (6,'Friendly ARM');
INSERT INTO "manufacturer" VALUES (7,'Stadium');
INSERT INTO "manufacturer" VALUES (8,'Sony Japan');
INSERT INTO "pin_mode" VALUES (0,'Input');
INSERT INTO "pin_mode" VALUES (1,'Output');
INSERT INTO "pin_mode" VALUES (2,'Disabled');
INSERT INTO "pin_mode" VALUES (3,'Pwm');
INSERT INTO "pin_mode" VALUES (4,'Alt0');
INSERT INTO "pin_mode" VALUES (5,'Alt1');
INSERT INTO "pin_mode" VALUES (6,'Alt2');
INSERT INTO "pin_mode" VALUES (7,'Alt3');
INSERT INTO "pin_mode" VALUES (8,'Alt4');
INSERT INTO "pin_mode" VALUES (9,'Alt5');
INSERT INTO "pin_mode" VALUES (10,'Alt6');
INSERT INTO "pin_mode" VALUES (11,'Alt7');
INSERT INTO "pin_mode" VALUES (12,'Alt8');
INSERT INTO "pin_mode" VALUES (13,'Alt9');
INSERT INTO "pin_type" VALUES (0,'Gpio');
INSERT INTO "pin_type" VALUES (1,'Power');
INSERT INTO "pin_type" VALUES (2,'Usb');
INSERT INTO "pin_type" VALUES (3,'Sound');
INSERT INTO "pin_type" VALUES (4,'Video');
INSERT INTO "pin_type" VALUES (5,'Not Connected');
INSERT INTO "pin_type" VALUES (6,'Net');
INSERT INTO "schema_version" VALUES (1,'2018-10-22 08:49:51','2018-10-23 09:46:59',0,3,1);
INSERT INTO "schema_version" VALUES (2,'2018-10-23 09:47:00','2025-04-27 20:49:59',0,3,2);
INSERT INTO "schema_version" VALUES (3,'2025-04-27 20:50:00',NULL,0,3,3);
INSERT INTO "soc_family" VALUES (-1,'Unknown',-1);
INSERT INTO "soc_family" VALUES (0,'Bcm283x',0);
INSERT INTO "soc_family" VALUES (1,'H-Series',0);
COMMIT;
