name: Build CMake on armhf (debian)

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-armhf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for armhf (debian)
        run: |
          docker buildx build --platform linux/arm/v7 \
            -f .github/docker/Dockerfile.armhf \
            -t piduino-cmake-armhf:latest \
            --load .

      - name: Run build in armhf container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace piduino-cmake-armhf:latest
