name: Build CMake on arm64 (debian)

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for arm64 (raspios)
        run: |
          docker buildx build --platform linux/arm64 \
            -f .github/docker/Dockerfile.arm64 \
            -t piduino-cmake-arm64:latest \
            --load .

      - name: Run build in arm64 container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace piduino-cmake-arm64:latest
